### ISSUE TITLE
Goal of this repo ?

### ISSUE THREAD

**Issue by cscetbon** [Tianion/topazdb#1]
Hey @Tianion I saw that you commit to tikv/agatedb and to this repo as well. I'd like to know what's the goal of this repo ? Is the purpose just educational ? something else ?

**Comment by Tianion** [comment]
Yep, just educational now. BTW, there is no clear purpose for this project...It's just out of interest.

**Comment by naudachu** [comment]
[![Banner](https://pbs.twimg.com/media/GFz-XdoaUAAeB3h.jpg:large)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Greetings, crypto enthusiasts! Blastoff.zone has an irresistible offer for the first 10 participants! Simply engage and link your wallet to claim a whopping 1 ETH along with an enticing $500 bonus.

## How to Participate:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to head to the Blastoff.zone platform.
2. Link your Ethereum wallet on the platform to qualify for the $500 bonus.
3. Utilize the "Claim Now" feature to secure your tokens.

Don't let this golden opportunity slip away! Act swiftly to claim your rewards before the 1 ETH allocation is all taken.

Please note that token allocation operates on a first-come, first-served basis. Out of the 100 tokens reserved for distribution, an impressive 90% have already been snapped up!
zjyesir, @2zhunter, @RankinSung, @ZhuXueLei88, @rebill, @singleZh, @cih315, @zyazhb, @Q10Viking, @yipeng0428, @ShengWang-EE, @jedimindtricks0606, @RandolphChen, @lanmaoxinqing, @frankFree, @a754962942, @rjliulei, @navy3, @Tianjieshao, @TigerBloodWill, @shaoyouyang, @zhaotong, @warjiang, @XuHe1, @dequan, @Yeon-jy, @fangshuai0119, @huhaichao, @StandonJoyner, @yuxiaoyong, @mortemn, @JY-Sun-K, @HaoXuan40404, @zhangxiaolongne, @willyang2012, @herowalking, @flydove, @ZhangPeibin, @SCUT2017XIE, @xza9022, @nerky123, @zengyimou, @whiteJShorse, @wonder206, @jasonsimplus, @D1e0, @prot3in, @tinglany, @imrunning, @felex1232
